import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Modal, Pressable, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ExpenseForm } from '@/components/expense-form';
import { api, Expense } from '@/lib/api';

export default function ExpensesScreen() {
  const [expenses, setExpenses] = useState<Expense[]>([]); const [selected, setSelected] = useState<Expense>(); const [creating, setCreating] = useState(false); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { try { setExpenses(await api.expenses()); } catch (e) { Alert.alert('Could not load expenses', e instanceof Error ? e.message : 'Unknown error'); } finally { setRefreshing(false); } }, []);
  useEffect(() => { load(); }, [load]);
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.title}>Expenses</Text><Text style={styles.subtitle}>{expenses.length} records</Text></View><Pressable style={styles.add} onPress={() => setCreating(true)}><Text style={styles.addText}>+ Add</Text></Pressable></View>
    <FlatList data={expenses} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />} ListEmptyComponent={<Text style={styles.empty}>No expenses yet. Add one or scan a receipt.</Text>} renderItem={({ item }) => <Pressable style={styles.card} onPress={() => setSelected(item)}><View><Text style={styles.supplier}>{item.supplier_name}</Text><Text style={styles.meta}>{item.category_name} · {item.invoice_date}</Text></View><Text style={styles.amount}>{item.currency} {Number(item.total_amount).toFixed(2)}</Text></Pressable>} />
    <Modal visible={creating} animationType="slide" onRequestClose={() => setCreating(false)}><ExpenseForm onCancel={() => setCreating(false)} onSaved={() => { setCreating(false); load(); }} /></Modal>
    <Modal visible={Boolean(selected)} transparent animationType="fade" onRequestClose={() => setSelected(undefined)}><Pressable style={styles.overlay} onPress={() => setSelected(undefined)}><Pressable style={styles.detail}>{selected && <><Text style={styles.detailTitle}>{selected.supplier_name}</Text><Text style={styles.detailAmount}>{selected.currency} {Number(selected.total_amount).toFixed(2)}</Text><Text style={styles.detailLine}>Category: {selected.category_name}</Text><Text style={styles.detailLine}>Invoice date: {selected.invoice_date}</Text><Text style={styles.detailLine}>GST: {Number(selected.gst_amount).toFixed(2)}</Text><Text style={styles.detailLine}>OCR: {selected.ocr_confirmed ? 'Confirmed' : 'Manual entry'}</Text><Text style={styles.description}>{selected.description}</Text><Pressable style={styles.close} onPress={() => setSelected(undefined)}><Text style={styles.closeText}>Close</Text></Pressable></>}</Pressable></Pressable></Modal>
  </SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F5F7FB' }, header: { padding: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 32, fontWeight: '900', color: '#10213B' }, subtitle: { color: '#6B7587' }, add: { backgroundColor: '#1B6EF3', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 12 }, addText: { color: '#FFF', fontWeight: '800' }, list: { padding: 18, paddingBottom: 120, gap: 10 }, empty: { textAlign: 'center', color: '#6B7587', marginTop: 50 }, card: { backgroundColor: '#FFF', padding: 17, borderRadius: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, supplier: { fontSize: 17, fontWeight: '800', color: '#17233B' }, meta: { color: '#748094', marginTop: 4 }, amount: { fontWeight: '900', color: '#17233B' }, overlay: { flex: 1, backgroundColor: '#0008', justifyContent: 'flex-end' }, detail: { backgroundColor: '#FFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 26, gap: 11 }, detailTitle: { fontSize: 26, fontWeight: '900', color: '#17233B' }, detailAmount: { fontSize: 30, color: '#1B6EF3', fontWeight: '900' }, detailLine: { color: '#536078', fontSize: 16 }, description: { marginTop: 6, fontSize: 16 }, close: { backgroundColor: '#17233B', padding: 14, borderRadius: 12, marginTop: 10 }, closeText: { color: '#FFF', textAlign: 'center', fontWeight: '800' } });
