import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, Modal, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ExpenseForm } from '@/components/expense-form';
import { api, Expense } from '@/lib/api';
import { ExpenseFilterState } from '@/lib/expense-filters';

export default function ExpensesScreen() {
  const [expenses, setExpenses] = useState<Expense[]>([]); const [selected, setSelected] = useState<Expense>(); const [editing, setEditing] = useState<Expense>(); const [creating, setCreating] = useState(false); const [refreshing, setRefreshing] = useState(false);
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState<ExpenseFilterState>({ search: '', ocr_confirmed: 'all' });
  const load = useCallback(async () => { try { setExpenses(await api.expenses(filters)); } catch (e) { Alert.alert('Could not load expenses', e instanceof Error ? e.message : 'Unknown error'); } finally { setRefreshing(false); } }, [filters]);
  useEffect(() => {
    // Initial remote data synchronization is intentionally started on mount.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    load();
  }, [load]);
  function remove(expense: Expense) {
    Alert.alert('Delete expense?', `${expense.supplier_name} will be permanently removed.`, [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Delete', style: 'destructive', onPress: () => void api.deleteExpense(expense.id).then(() => { setSelected(undefined); load(); }).catch((error) => Alert.alert('Could not delete', error instanceof Error ? error.message : 'Unknown error')) },
    ]);
  }
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.title}>Expenses</Text><Text style={styles.subtitle}>{expenses.length} records</Text></View><Pressable style={styles.add} onPress={() => setCreating(true)}><Text style={styles.addText}>+ Add</Text></Pressable></View>
    <View style={styles.filters}><TextInput placeholder="Search supplier or description" value={search} onChangeText={setSearch} onSubmitEditing={() => setFilters((current) => ({ ...current, search }))} returnKeyType="search" style={styles.search} /><View style={styles.filterRow}>{(['all', 'confirmed', 'draft'] as const).map((status) => <Pressable key={status} onPress={() => setFilters((current) => ({ ...current, ocr_confirmed: status }))} style={[styles.filterChip, filters.ocr_confirmed === status && styles.filterChipActive]}><Text style={filters.ocr_confirmed === status ? styles.filterTextActive : styles.filterText}>{status === 'all' ? 'All' : status === 'confirmed' ? 'Confirmed' : 'Drafts'}</Text></Pressable>)}<Pressable onPress={() => setFilters((current) => ({ ...current, search }))} style={styles.apply}><Text style={styles.applyText}>Apply</Text></Pressable></View></View>
    <FlatList data={expenses} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} />} ListEmptyComponent={<Text style={styles.empty}>No expenses yet. Add one or scan a receipt.</Text>} renderItem={({ item }) => <Pressable style={styles.card} onPress={() => setSelected(item)}><View><Text style={styles.supplier}>{item.supplier_name}</Text><Text style={styles.meta}>{item.category_name} · {item.invoice_date}</Text></View><Text style={styles.amount}>{item.currency} {Number(item.total_amount).toFixed(2)}</Text></Pressable>} />
    <Modal visible={creating} animationType="slide" onRequestClose={() => setCreating(false)}><ExpenseForm onCancel={() => setCreating(false)} onSaved={() => { setCreating(false); load(); }} /></Modal>
    <Modal visible={Boolean(editing)} animationType="slide" onRequestClose={() => setEditing(undefined)}>{editing && <ExpenseForm expense={editing} onCancel={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); load(); }} />}</Modal>
    <Modal visible={Boolean(selected)} transparent animationType="fade" onRequestClose={() => setSelected(undefined)}><Pressable style={styles.overlay} onPress={() => setSelected(undefined)}><Pressable style={styles.detail}>{selected && <><Text style={styles.detailTitle}>{selected.supplier_name}</Text><Text style={styles.detailAmount}>{selected.currency} {Number(selected.total_amount).toFixed(2)}</Text><Text style={styles.detailLine}>Category: {selected.category_name}</Text><Text style={styles.detailLine}>Invoice date: {selected.invoice_date}</Text><Text style={styles.detailLine}>GST: {Number(selected.gst_amount).toFixed(2)}</Text><Text style={styles.detailLine}>OCR: {selected.ocr_confirmed ? 'Confirmed' : 'Manual entry'}</Text><Text style={styles.description}>{selected.description}</Text><View style={styles.detailActions}><Pressable style={styles.edit} onPress={() => { setEditing(selected); setSelected(undefined); }}><Text style={styles.editText}>Edit</Text></Pressable><Pressable style={styles.delete} onPress={() => remove(selected)}><Text style={styles.deleteText}>Delete</Text></Pressable></View><Pressable style={styles.close} onPress={() => setSelected(undefined)}><Text style={styles.closeText}>Close</Text></Pressable></>}</Pressable></Pressable></Modal>
  </SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#F5F7FB' }, header: { padding: 22, paddingBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, title: { fontSize: 32, fontWeight: '900', color: '#10213B' }, subtitle: { color: '#6B7587' }, add: { backgroundColor: '#1B6EF3', paddingHorizontal: 18, paddingVertical: 12, borderRadius: 12 }, addText: { color: '#FFF', fontWeight: '800' }, filters: { paddingHorizontal: 18, gap: 9 }, search: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#D8DEE9', borderRadius: 12, padding: 12, fontSize: 15 }, filterRow: { flexDirection: 'row', gap: 7, alignItems: 'center' }, filterChip: { borderWidth: 1, borderColor: '#C8D0DC', borderRadius: 18, paddingHorizontal: 10, paddingVertical: 7 }, filterChipActive: { backgroundColor: '#17233B', borderColor: '#17233B' }, filterText: { color: '#536078', fontWeight: '700' }, filterTextActive: { color: '#FFF', fontWeight: '800' }, apply: { marginLeft: 'auto', backgroundColor: '#1B6EF3', borderRadius: 10, paddingHorizontal: 13, paddingVertical: 8 }, applyText: { color: '#FFF', fontWeight: '800' }, list: { padding: 18, paddingBottom: 120, gap: 10 }, empty: { textAlign: 'center', color: '#6B7587', marginTop: 50 }, card: { backgroundColor: '#FFF', padding: 17, borderRadius: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, supplier: { fontSize: 17, fontWeight: '800', color: '#17233B' }, meta: { color: '#748094', marginTop: 4 }, amount: { fontWeight: '900', color: '#17233B' }, overlay: { flex: 1, backgroundColor: '#0008', justifyContent: 'flex-end' }, detail: { backgroundColor: '#FFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 26, gap: 11 }, detailTitle: { fontSize: 26, fontWeight: '900', color: '#17233B' }, detailAmount: { fontSize: 30, color: '#1B6EF3', fontWeight: '900' }, detailLine: { color: '#536078', fontSize: 16 }, description: { marginTop: 6, fontSize: 16 }, detailActions: { flexDirection: 'row', gap: 10, marginTop: 8 }, edit: { flex: 1, backgroundColor: '#E8F0FF', padding: 12, borderRadius: 10 }, editText: { color: '#1B6EF3', textAlign: 'center', fontWeight: '800' }, delete: { flex: 1, backgroundColor: '#FEE4E2', padding: 12, borderRadius: 10 }, deleteText: { color: '#B42318', textAlign: 'center', fontWeight: '800' }, close: { backgroundColor: '#17233B', padding: 14, borderRadius: 12, marginTop: 2 }, closeText: { color: '#FFF', textAlign: 'center', fontWeight: '800' } });
